//
//  DeveloperPreview.swift
//  AirbnbClone
//
//  Created by Andre on 27/07/25.
//

import Foundation

class DeveloperPreview{
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 4,
            numberOfGuests: 4,
            numberOfBeds: 3,
            pricePerNight: 567,
            latitude: 25.7850,
            longitude: -80.1936,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "123 Main St",
            city: "Miami",
            state: "Florida",
            title: "Miami Villa",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sarah Johnson",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 234,
            latitude: 40.7128,
            longitude: -74.0060,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "456 Broadway",
            city: "New York",
            state: "New York",
            title: "Cozy Manhattan Apartment",
            rating: 4.72,
            features: [.selfCheckIn],
            amenities: [.wifi, .kitchen, .tv, .office],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Michael Chen",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 189,
            latitude: 37.7749,
            longitude: -122.4194,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "789 Market St",
            city: "San Francisco",
            state: "California",
            title: "Modern Studio in SOMA",
            rating: 4.91,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Emily Rodriguez",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 298,
            latitude: 34.0522,
            longitude: -118.2437,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "321 Sunset Blvd",
            city: "Los Angeles",
            state: "California",
            title: "Hollywood Hills House",
            rating: 4.65,
            features: [.superHost],
            amenities: [.wifi, .pool, .balcony, .kitchen, .pool, .office],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "David Williams",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 5,
            numberOfBathrooms: 3,
            numberOfGuests: 10,
            numberOfBeds: 6,
            pricePerNight: 445,
            latitude: 41.8781,
            longitude: -87.6298,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "654 Lake Shore Dr",
            city: "Chicago",
            state: "Illinois",
            title: "Lakefront Family Home",
            rating: 4.78,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .balcony, .laundry, .tv, .office],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Lisa Park",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 156,
            latitude: 30.2672,
            longitude: -97.7431,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "987 South Lamar",
            city: "Austin",
            state: "Texas",
            title: "Trendy South Austin Loft",
            rating: 4.83,
            features: [.selfCheckIn],
            amenities: [.wifi, .kitchen, .office, .tv, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Robert Taylor",
            ownerImageUrl: "male-profile-photo-4",
            numberOfBedrooms: 2,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 312,
            latitude: 47.6062,
            longitude: -122.3321,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "147 Pine St",
            city: "Seattle",
            state: "Washington",
            title: "Downtown Seattle Condo",
            rating: 4.69,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .balcony, .tv, .pool],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Maria Gonzalez",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            pricePerNight: 389,
            latitude: 36.1627,
            longitude: -86.7816,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "258 Music Row",
            city: "Nashville",
            state: "Tennessee",
            title: "Music City Townhouse",
            rating: 4.74,
            features: [.superHost],
            amenities: [.wifi, .kitchen, .balcony, .laundry, .tv],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "James Anderson",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 6,
            numberOfBathrooms: 4,
            numberOfGuests: 12,
            numberOfBeds: 8,
            pricePerNight: 678,
            latitude: 33.4484,
            longitude: -112.0740,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "369 Desert View Rd",
            city: "Phoenix",
            state: "Arizona",
            title: "Desert Oasis Villa",
            rating: 4.88,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .pool, .balcony, .kitchen, .tv, .pool],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jennifer Lee",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 145,
            latitude: 39.7392,
            longitude: -104.9903,
            imageUrls: ["listing-2","listing-1", "listing-3","listing-4","listing-5", "listing-6"],
            address: "741 16th Street Mall",
            city: "Denver",
            state: "Colorado",
            title: "Mountain View Studio",
            rating: 4.67,
            features: [.selfCheckIn],
            amenities: [.wifi, .kitchen, .office, .tv, .pool],
            type: .apartment
        )
    ]
}
